### ISSUE TITLE
Is compton tryone available for ubuntu

### ISSUE THREAD

**Issue by jchannon** [WillPower3309/dotfiles#2]
Google fu suggests no but just wondered if you knew? Thanks

**Comment by WillPower3309** [comment]
Good news and bad news! The good news is you can get compton tryone on ubuntu! The bad news is you gotta compile it yourself. There are some instructions in the [readme](https://github.com/tryone144/compton) to do so.

It's worth noting that the dev is working on bringing his blur to [picom](https://github.com/yshui/picom), a new and improved compositor based on the now outdated compton, so if you're having trouble building compton tryone, you can wait for it to be merged with picom and just use picom as your compositor.

**Comment by jchannon** [comment]
Is the PR up (doesn't seem so) to merge into picom?

Will give compiling a go!

Thanks for the dotfiles!!

**Comment by WillPower3309** [comment]
Not yet! It's on the road-map and close iirc. He already has a branch working with picom so should be relatively soon. If you run into any issues compiling shoot me a message and ill be happy to try and help!

Glad you enjoy!
